apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp
  namespace: default
spec:
  replicas: 1
  template:
    spec: # Pod spec
      containers:
        - name: mycontainer
          image: node-app:1.0
          ports:
            - containerPort: 80
          # Reference ConfigMap data at appropriate path (/etc/config)
          volumeMounts:
            - name: app-config-vol
              mountPath: /etc/config
          resources:
            requests:
              memory: "16Mi"
              cpu: "50m" # 500milliCPUs (1/2 CPU)
            limits:
              memory: "128Mi"
              cpu: "100m"
          envFrom:
            - configMapRef:
                name: mykustom-map
      # Define volume that will contain ConfigMap data
      volumes:
        - name: app-config-vol
          configMap:
            name: mykustom-map
