apiVersion: v1
kind: Service
metadata:
  name: mywebapp # Ensure this matches the name in base/service.yaml
spec:
  ports:
    - port: 80
      targetPort: 9000 # Keep targetPort consistent
      protocol: TCP
      name: node-app
